# DEVELOPMENT ONLY!
# do not use this in production!
# changing files within the container will not restart the app
# gem listen is the issue with containers
version: '2'
services:
  cafmal-web:
    build: .
    ports:
      - "3000:3000"
    environment:
      - RACK_ENV=development
      - SECRET_KEY_BASE=bd43a0b6c77911978dfcf2d13b7467asdasdasd602c45abd612ebb2d8as9b7f8a244730def09a5c70573a3dbea6387248ec100aa2ae244730def0673707696f13e5e
